package com.careerly.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.jsonwebtoken.Claims;
import jakarta.transaction.Transactional;
import lombok.*;
import org.springframework.http.*;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.io.*;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.stream.*;

@RestController @RequestMapping("/api") @RequiredArgsConstructor
class ApiController {
  private final UserRepository users; private final CandidateProfileRepository candidates; private final EmployerProfileRepository employers; private final CompanyRepository companies; private final CompanyDocumentRepository documents; private final JobRepository jobs; private final JobApplicationRepository applications; private final TokenService tokens;
  private final BCryptPasswordEncoder passwords=new BCryptPasswordEncoder();
  private Claims auth(String header,String role){ Claims c=tokens.claims(header); if(role!=null&&!role.equals(c.get("accountType",String.class))) fail(HttpStatus.FORBIDDEN,"This account cannot access the requested resource."); return c; }
  private UserAccount user(Claims c){return users.findById(Long.valueOf(c.getSubject())).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Account not found."));}
  private RuntimeException error(HttpStatus s,String message){return new org.springframework.web.server.ResponseStatusException(s,message);}
  private void fail(HttpStatus s,String message){throw error(s,message);}
  private String text(Map<String,?> body,String key){Object v=body.get(key);return v==null?"":String.valueOf(v).trim();}
  private void require(Map<String,?> body,String... fields){List<String> missing=Arrays.stream(fields).filter(f->text(body,f).isBlank()).toList();if(!missing.isEmpty())fail(HttpStatus.BAD_REQUEST,"Missing required fields: "+String.join(", ",missing));}
  private Map<String,Object> companyJson(Company c){return Map.of("id",c.getId(),"legalName",c.getLegalName(),"brandName",Optional.ofNullable(c.getBrandName()).orElse(""),"website",c.getWebsite(),"companyType",c.getCompanyType(),"industry",c.getIndustry(),"companySize",c.getCompanySize(),"description",c.getDescription(),"city",c.getCity(),"state",c.getState(),"verificationStatus",c.getVerificationStatus(),"createdAt",c.getCreatedAt());}
  private Map<String,Object> jobJson(Job j){Map<String,Object> m=new LinkedHashMap<>();m.put("id",j.getId());m.put("companyId",j.getCompany().getId());m.put("title",j.getTitle());m.put("department",Optional.ofNullable(j.getDepartment()).orElse(""));m.put("description",j.getDescription());m.put("employmentType",j.getEmploymentType());m.put("workModel",j.getWorkModel());m.put("city",Optional.ofNullable(j.getCity()).orElse(""));m.put("state",Optional.ofNullable(j.getState()).orElse(""));m.put("country",j.getCountry());m.put("minExperienceYears",j.getMinExperienceYears());m.put("maxExperienceYears",j.getMaxExperienceYears());m.put("salaryMin",j.getSalaryMin());m.put("salaryMax",j.getSalaryMax());m.put("currency",j.getCurrency());m.put("status",j.getStatus());m.put("skills",j.getSkills().stream().map(JobSkill::getSkillName).toList());m.put("company",companyJson(j.getCompany()));return m;}

  @GetMapping("/health") Map<String,String> health(){return Map.of("status","ok","database","mysql");}
  @PostMapping("/job-seekers/register") @Transactional ResponseEntity<?> registerCandidate(@RequestBody Map<String,Object> b){require(b,"firstName","lastName","email","password","confirmPassword");if(text(b,"password").length()<8)fail(HttpStatus.BAD_REQUEST,"Password must contain at least 8 characters.");if(!text(b,"password").equals(text(b,"confirmPassword")))fail(HttpStatus.BAD_REQUEST,"Passwords do not match.");String email=text(b,"email").toLowerCase();if(users.findByEmailIgnoreCase(email).isPresent())fail(HttpStatus.CONFLICT,"An account already exists for this email.");UserAccount u=new UserAccount();u.setEmail(email);u.setPasswordHash(passwords.encode(text(b,"password")));u.setAccountType("job_seeker");users.save(u);CandidateProfile p=new CandidateProfile();p.setUser(u);p.setFirstName(text(b,"firstName"));p.setLastName(text(b,"lastName"));candidates.save(p);return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Job seeker account created.","accessToken",tokens.issue(u,null),"user",Map.of("id",u.getId(),"email",email,"accountType","job_seeker","firstName",p.getFirstName(),"lastName",p.getLastName())));}
  @PostMapping(value="/employers/register",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @Transactional ResponseEntity<?> registerEmployer(@RequestParam Map<String,String> b,@RequestPart MultipartFile document){require(b,"firstName","lastName","workEmail","phone","designation","password","confirmPassword","legalName","website","companyType","industry","companySize","address","city","state","postalCode","companyAbout","documentType");if(document==null||document.isEmpty()||!b.containsKey("authorization")||!b.containsKey("terms"))fail(HttpStatus.BAD_REQUEST,"Complete all required company, document, and authorization fields.");if(!text(b,"password").equals(text(b,"confirmPassword")))fail(HttpStatus.BAD_REQUEST,"Passwords do not match.");String email=text(b,"workEmail").toLowerCase();if(users.findByEmailIgnoreCase(email).isPresent())fail(HttpStatus.CONFLICT,"This work email is already registered.");Company c=new Company();c.setLegalName(text(b,"legalName"));c.setBrandName(text(b,"brandName"));c.setWebsite(text(b,"website"));c.setCompanyType(text(b,"companyType"));c.setIndustry(text(b,"industry"));c.setCompanySize(text(b,"companySize"));c.setDescription(text(b,"companyAbout"));c.setAddress(text(b,"address"));c.setCity(text(b,"city"));c.setState(text(b,"state"));c.setPostalCode(text(b,"postalCode"));c.setCin(text(b,"cin"));c.setGstin(text(b,"gstin"));c.setVerificationStatus("pending");companies.save(c);UserAccount u=new UserAccount();u.setEmail(email);u.setPasswordHash(passwords.encode(text(b,"password")));u.setAccountType("employer");users.save(u);EmployerProfile ep=new EmployerProfile();ep.setUser(u);ep.setCompany(c);ep.setFirstName(text(b,"firstName"));ep.setLastName(text(b,"lastName"));ep.setPhone(text(b,"phone"));ep.setPhoneCountryCode(Optional.ofNullable(text(b,"phoneCountryCode")).filter(s->!s.isBlank()).orElse("+91"));ep.setDesignation(text(b,"designation"));employers.save(ep);CompanyDocument d=new CompanyDocument();d.setCompany(c);d.setUploadedBy(u);d.setDocumentType(text(b,"documentType"));d.setOriginalFileName(document.getOriginalFilename());d.setStoredFileName(UUID.randomUUID()+"-"+document.getOriginalFilename());d.setStoredPath(d.getStoredFileName());d.setMimeType(document.getContentType());d.setFileSizeBytes(document.getSize());documents.save(d);return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Company registration submitted for verification.","applicationReference",String.format("CAR-EMP-%06d",c.getId()),"company",Map.of("id",c.getId(),"legalName",c.getLegalName(),"verificationStatus","pending")));}
  @PostMapping("/auth/login") @Transactional ResponseEntity<?> login(@RequestBody Map<String,Object> b){String email=text(b,"email").toLowerCase();UserAccount u=users.findByEmailIgnoreCase(email).orElseThrow(()->error(HttpStatus.UNAUTHORIZED,"Incorrect email or password."));if(!passwords.matches(text(b,"password"),u.getPasswordHash()))fail(HttpStatus.UNAUTHORIZED,"Incorrect email or password.");if(!text(b,"accountType").isBlank()&&!text(b,"accountType").equals(u.getAccountType()))fail(HttpStatus.FORBIDDEN,"This email is registered as a "+u.getAccountType().replace('_',' ')+" account.");u.setLastLoginAt(Instant.now());EmployerProfile ep=employers.findByUser_Id(u.getId()).orElse(null);Map<String,Object> response=new LinkedHashMap<>();response.put("message","Signed in successfully.");response.put("accessToken",tokens.issue(u,ep==null?null:ep.getCompany().getId()));response.put("user",Map.of("id",u.getId(),"email",u.getEmail(),"accountType",u.getAccountType()));response.put("company",ep==null?null:companyJson(ep.getCompany()));return ResponseEntity.ok(response);}
  @GetMapping("/me") Map<String,Object> me(@RequestHeader("Authorization") String h){UserAccount u=user(auth(h,null));return Map.of("user",Map.of("id",u.getId(),"email",u.getEmail(),"accountType",u.getAccountType(),"accountStatus",u.getAccountStatus(),"createdAt",u.getCreatedAt()));}
  @GetMapping("/companies") Map<String,Object> companyList(){List<Map<String,Object>> list=companies.findAll().stream().sorted(Comparator.comparing(Company::getCreatedAt,Comparator.nullsLast(Comparator.reverseOrder()))).map(c->{Map<String,Object> m=new LinkedHashMap<>(companyJson(c));m.put("jobCount",jobs.findByCompanyId(c.getId()).stream().filter(j->"published".equals(j.getStatus())).count());return m;}).toList();return Map.of("companies",list,"total",list.size());}
  @GetMapping("/companies/{id}") Map<String,Object> company(@PathVariable Long id){Company c=companies.findById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Company not found."));Map<String,Object> result=new LinkedHashMap<>(companyJson(c));result.put("jobCount",jobs.findByCompanyId(c.getId()).stream().filter(j->"published".equals(j.getStatus())).count());return Map.of("company",result);}
  @GetMapping("/jobs") Map<String,Object> jobList(@RequestParam(required=false) String q,@RequestParam(required=false) String location,@RequestParam(required=false) Long companyId){String term=Optional.ofNullable(q).orElse("").toLowerCase();String place=Optional.ofNullable(location).orElse("").toLowerCase();Stream<Job> stream=(companyId==null?jobs.findByStatus("published").stream():jobs.findByCompanyId(companyId).stream().filter(j->"published".equals(j.getStatus())));List<Map<String,Object>> list=stream.filter(j->(j.getTitle()+" "+j.getDescription()+" "+j.getCompany().getLegalName()).toLowerCase().contains(term)).filter(j->(Optional.ofNullable(j.getCity()).orElse("")+" "+Optional.ofNullable(j.getState()).orElse("")+" "+j.getWorkModel()).toLowerCase().contains(place)).map(this::jobJson).toList();return Map.of("jobs",list,"total",list.size());}
  @GetMapping("/job-seekers/me") Map<String,Object> candidateMe(@RequestHeader("Authorization") String h){UserAccount u=user(auth(h,"job_seeker"));CandidateProfile p=candidates.findByUser_Id(u.getId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Job seeker profile not found."));return Map.of("profile",candidateJson(p),"completion",Map.of("percentage",completion(p),"items",List.of()));}
  @PutMapping(value="/job-seekers/me",consumes={MediaType.APPLICATION_JSON_VALUE,MediaType.MULTIPART_FORM_DATA_VALUE}) @Transactional Map<String,Object> updateCandidate(@RequestHeader("Authorization") String h,@RequestBody(required=false) Map<String,Object> b){UserAccount u=user(auth(h,"job_seeker"));CandidateProfile p=candidates.findByUser_Id(u.getId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Job seeker profile not found."));if(b!=null){p.setFirstName(text(b,"firstName"));p.setLastName(text(b,"lastName"));p.setPhone(text(b,"phone"));p.setHeadline(text(b,"headline"));p.setProfessionalSummary(text(b,"professionalSummary"));p.setCity(text(b,"city"));p.setState(text(b,"state"));p.setCountry(Optional.ofNullable(text(b,"country")).filter(v->!v.isBlank()).orElse("India"));p.setCurrentCompany(text(b,"currentCompany"));p.setCurrentJobTitle(text(b,"currentJobTitle"));p.setPortfolioUrl(text(b,"portfolioUrl"));p.setLinkedinUrl(text(b,"linkedinUrl"));p.setEmploymentStatus(text(b,"employmentStatus"));p.setSalaryExpectation(text(b,"salaryExpectation"));p.setNoticePeriod(text(b,"noticePeriod"));p.setProfileVisibility(Optional.ofNullable(text(b,"profileVisibility")).filter(v->!v.isBlank()).orElse("employers_only"));}candidates.save(p);return Map.of("message","Profile saved successfully.","profile",candidateJson(p),"completion",Map.of("percentage",completion(p),"items",List.of()));}
  @PostMapping("/jobs/{id}/applications") @Transactional ResponseEntity<?> apply(@RequestHeader("Authorization") String h,@PathVariable Long id,@RequestBody(required=false) Map<String,Object> b){UserAccount u=user(auth(h,"job_seeker"));Job j=jobs.findById(id).filter(x->"published".equals(x.getStatus())).orElseThrow(()->error(HttpStatus.NOT_FOUND,"This vacancy is no longer available."));if(applications.existsByJobIdAndCandidateId(id,u.getId()))fail(HttpStatus.CONFLICT,"You have already applied for this job.");JobApplication a=new JobApplication();a.setJob(j);a.setCandidate(u);a.setCoverLetter(b==null?"":text(b,"coverLetter"));applications.save(a);return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Application submitted.","application",Map.of("id",a.getId(),"jobId",j.getId(),"status",a.getStatus())));}
  @PostMapping("/employer/jobs") @Transactional ResponseEntity<?> postJob(@RequestHeader("Authorization") String h,@RequestBody Map<String,Object> b){UserAccount u=user(auth(h,"employer"));EmployerProfile ep=employers.findByUser_Id(u.getId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Employer profile not found."));require(b,"title","description","employmentType","workModel");Job j=new Job();j.setCompany(ep.getCompany());j.setCreatedBy(u);j.setTitle(text(b,"title"));j.setDepartment(text(b,"department"));j.setDescription(text(b,"description"));j.setEmploymentType(text(b,"employmentType"));j.setWorkModel(text(b,"workModel"));j.setCity(text(b,"city"));j.setState(text(b,"state"));j.setStatus("published");j.setPublishedAt(Instant.now());String[] skillList=text(b,"skills").split(",");for(int i=0;i<skillList.length;i++){if(!skillList[i].trim().isBlank()){JobSkill s=new JobSkill();s.setJob(j);s.setSkillName(skillList[i].trim());s.setSortOrder(i);j.getSkills().add(s);}}jobs.save(j);return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Job published.","job",jobJson(j)));}
  @GetMapping("/employer/dashboard") Map<String,Object> dashboard(@RequestHeader("Authorization") String h){UserAccount u=user(auth(h,"employer"));EmployerProfile ep=employers.findByUser_Id(u.getId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"Employer profile not found."));List<Job> own=jobs.findByCompanyId(ep.getCompany().getId());List<JobApplication> app=applications.findByJobCompanyId(ep.getCompany().getId());return Map.of("employer",Map.of("firstName",ep.getFirstName(),"lastName",ep.getLastName(),"designation",ep.getDesignation()),"company",companyJson(ep.getCompany()),"metrics",Map.of("activeJobs",own.stream().filter(j->"published".equals(j.getStatus())).count(),"applications",app.size(),"shortlisted",app.stream().filter(a->"shortlisted".equals(a.getStatus())).count()),"jobs",own.stream().map(this::jobJson).toList(),"applications",List.of());}
  private Map<String,Object> candidateJson(CandidateProfile p){Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("userId",p.getUser().getId());m.put("email",p.getUser().getEmail());m.put("firstName",p.getFirstName());m.put("lastName",p.getLastName());m.put("phone",Optional.ofNullable(p.getPhone()).orElse(""));m.put("headline",Optional.ofNullable(p.getHeadline()).orElse(""));m.put("professionalSummary",Optional.ofNullable(p.getProfessionalSummary()).orElse(""));m.put("city",Optional.ofNullable(p.getCity()).orElse(""));m.put("state",Optional.ofNullable(p.getState()).orElse(""));m.put("country",p.getCountry());m.put("experience",List.of());m.put("education",List.of());m.put("skills",List.of());m.put("languages",List.of());m.put("projects",List.of());m.put("certifications",List.of());m.put("preferredRoles",List.of());m.put("preferredLocations",List.of());m.put("workModes",List.of());return m;}
  private int completion(CandidateProfile p){int n=0;if(p.getFirstName()!=null&&!p.getFirstName().isBlank()&&p.getLastName()!=null&&!p.getLastName().isBlank()&&p.getPhone()!=null&&!p.getPhone().isBlank())n+=10;if(p.getHeadline()!=null&&!p.getHeadline().isBlank())n+=10;if(p.getProfessionalSummary()!=null&&p.getProfessionalSummary().length()>=50)n+=10;if(p.getCity()!=null&&!p.getCity().isBlank())n+=10;return n;}
}
