package com.careerly.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.*;
import java.util.*;

@Entity @Table(name="companies") @Getter @Setter @NoArgsConstructor
class Company {
  @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="legal_name",nullable=false) String legalName; @Column(name="brand_name") String brandName; @Column(nullable=false) String website; @Column(name="company_type",nullable=false) String companyType; @Column(nullable=false) String industry; @Column(name="company_size",nullable=false) String companySize; @Column(name="founded_year") Integer foundedYear; @Column(nullable=false,length=2000) String description; @Column(name="registered_address",nullable=false) String address; @Column(nullable=false) String city; @Column(nullable=false) String state; String country="India"; @Column(name="postal_code",nullable=false) String postalCode; String cin; String gstin; @Column(name="verification_status") String verificationStatus="pending"; @Column(name="created_at") Instant createdAt; @PrePersist void created(){if(createdAt==null)createdAt=Instant.now();}
}
@Entity @Table(name="job_seeker_profiles") @Getter @Setter @NoArgsConstructor
class CandidateProfile { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @OneToOne @JoinColumn(name="user_id") UserAccount user; @Column(name="first_name") String firstName; @Column(name="last_name") String lastName; String phone; String headline; @Column(name="professional_summary",length=4000) String professionalSummary; String city; String state; String country="India"; @Column(name="experience_years") Double experienceYears; @Column(name="current_company") String currentCompany; @Column(name="current_job_title") String currentJobTitle; @Column(name="portfolio_url") String portfolioUrl; @Column(name="linkedin_url") String linkedinUrl; @Column(name="employment_status") String employmentStatus; @Column(name="salary_expectation") String salaryExpectation; @Column(name="notice_period") String noticePeriod; @Column(name="resume_path") String resumePath; @Column(name="resume_original_name") String resumeOriginalName; @Column(name="resume_mime_type") String resumeMimeType; @Column(name="profile_photo_path") String profilePhotoPath; @Column(name="profile_photo_mime_type") String profilePhotoMimeType; @Column(name="profile_visibility") String profileVisibility="employers_only"; }
@Entity @Table(name="employer_profiles") @Getter @Setter @NoArgsConstructor
class EmployerProfile { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @OneToOne @JoinColumn(name="user_id") UserAccount user; @ManyToOne @JoinColumn(name="company_id") Company company; @Column(name="first_name") String firstName; @Column(name="last_name") String lastName; @Column(name="phone_country_code") String phoneCountryCode="+91"; String phone; String designation; }
@Entity @Table(name="company_documents") @Getter @Setter @NoArgsConstructor
class CompanyDocument { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="company_id") Company company; @ManyToOne @JoinColumn(name="uploaded_by_user_id") UserAccount uploadedBy; @Column(name="document_type") String documentType; @Column(name="original_file_name") String originalFileName; @Column(name="stored_file_name") String storedFileName; @Column(name="stored_path") String storedPath; @Column(name="mime_type") String mimeType; @Column(name="file_size_bytes") Long fileSizeBytes; }
@Entity @Table(name="jobs") @Getter @Setter @NoArgsConstructor
class Job { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="company_id") Company company; @ManyToOne @JoinColumn(name="created_by_user_id") UserAccount createdBy; String title; String department; @Column(length=6000) String description; @Column(name="employment_type") String employmentType; @Column(name="work_model") String workModel; String city; String state; String country="India"; @Column(name="min_experience_years") Double minExperienceYears; @Column(name="max_experience_years") Double maxExperienceYears; @Column(name="salary_min") Double salaryMin; @Column(name="salary_max") Double salaryMax; String currency="INR"; String status="published"; @Column(name="published_at") Instant publishedAt; @OneToMany(mappedBy="job",cascade=CascadeType.ALL,orphanRemoval=true) List<JobSkill> skills=new ArrayList<>(); }
@Entity @Table(name="job_skills") @Getter @Setter @NoArgsConstructor
class JobSkill { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="job_id") Job job; @Column(name="skill_name") String skillName; @Column(name="sort_order") Integer sortOrder; }
@Entity @Table(name="job_applications") @Getter @Setter @NoArgsConstructor
class JobApplication { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="job_id") Job job; @ManyToOne @JoinColumn(name="job_seeker_user_id") UserAccount candidate; @Column(name="cover_letter") String coverLetter; @Column(name="resume_path") String resumePath; String status="submitted"; @Column(name="applied_at") Instant appliedAt; @PrePersist void created(){if(appliedAt==null)appliedAt=Instant.now();} }
