package com.careerly.model;
import jakarta.persistence.*;
import lombok.*;

/** Direct mappings for the remaining normalized Careerly tables. */
@MappedSuperclass @Getter @Setter class ProfileChild { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="job_seeker_profile_id") CandidateProfile profile; }
@Entity @Table(name="candidate_work_experiences") @Getter @Setter class CandidateWorkExperience extends ProfileChild { @Column(name="job_title") String title; @Column(name="company_name") String company; String location; @Column(name="start_date") String startDate; @Column(name="end_date") String endDate; String description; @Column(name="sort_order") Integer sortOrder; }
@Entity @Table(name="candidate_educations") @Getter @Setter class CandidateEducation extends ProfileChild { String degree; @Column(name="field_of_study") String fieldOfStudy; String institution; @Column(name="start_year") String startYear; @Column(name="end_year") String endYear; String grade; @Column(name="sort_order") Integer sortOrder; }
@Entity @Table(name="candidate_skills") @Getter @Setter class CandidateSkill extends ProfileChild { @Column(name="skill_name") String skillName; }
@Entity @Table(name="candidate_projects") @Getter @Setter class CandidateProject extends ProfileChild { @Column(name="project_name") String projectName; @Column(name="role_name") String roleName; @Column(name="project_url") String projectUrl; String description; @Column(name="sort_order") Integer sortOrder; }
@Entity @Table(name="candidate_certifications") @Getter @Setter class CandidateCertification extends ProfileChild { @Column(name="certification_name") String certificationName; String issuer; @Column(name="issue_year") String issueYear; @Column(name="credential_url") String credentialUrl; @Column(name="sort_order") Integer sortOrder; }
@Entity @Table(name="candidate_languages") @Getter @Setter class CandidateLanguage extends ProfileChild { @Column(name="language_name") String languageName; }
@Entity @Table(name="candidate_job_preferences") @Getter @Setter class CandidateJobPreference { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @OneToOne @JoinColumn(name="job_seeker_profile_id") CandidateProfile profile; }
@Entity @Table(name="hiring_preferences") @Getter @Setter class HiringPreference { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @OneToOne @JoinColumn(name="company_id") Company company; @Column(name="expected_hires") String expectedHires; @Column(name="hiring_start_timeline") String startTimeline; @Column(name="work_model") String workModel; @Column(name="primary_hiring_location") String location; @Column(name="experience_level") String experienceLevel; }
@Entity @Table(name="hiring_preference_teams") @Getter @Setter class HiringPreferenceTeam { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="hiring_preference_id") HiringPreference preference; @Column(name="team_name") String teamName; }
@Entity @Table(name="audit_logs") @Getter @Setter class AuditLog { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @ManyToOne @JoinColumn(name="user_id") UserAccount user; String action; @Column(name="entity_type") String entityType; @Column(name="entity_id") Long entityId; @Column(name="ip_address") String ipAddress; String metadata; }
